version: "3.3"

services:
  chat_app:
    ports:
      - 3001:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: